# AI-Powered Smart Retail & Customer Intelligence Platform

## Module 2: Customer Review Sentiment Analysis

### Objective
This notebook builds a Machine Learning model that classifies customer reviews into positive or negative sentiments.

### Technologies
- Python
- Scikit-learn
- TF-IDF Vectorizer
- Logistic Regression

In [ ]:
!pip install pandas scikit-learn matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
reviews = [
    "Amazing quality",
    "Very bad product",
    "Fast delivery",
    "Delivery was very late",
    "Excellent service",
    "Worst experience",
    "Highly recommended",
    "Poor packaging",
    "Loved the product",
    "Not worth the money",
    "Fantastic quality",
    "Very disappointed",
    "Good customer support",
    "Terrible product",
    "Excellent packaging"
]

labels = [
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive",
    "Negative",
    "Positive"
]

df = pd.DataFrame({
    "Review": reviews,
    "Sentiment": labels
})

df.head()

                   Review Sentiment
0         Amazing quality  Positive
1        Very bad product  Negative
2           Fast delivery  Positive
3  Delivery was very late  Negative
4       Excellent service  Positive

In [ ]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["Review"])

y = df["Sentiment"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy: 0.3333333333333333
              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00         2
    Positive       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.17      0.50      0.25         3
weighted avg       0.11      0.33      0.17         3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
review = ["The delivery was very late"]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print("Review:", review[0])
print("Predicted Sentiment:", prediction[0])

Review: The delivery was very late
Predicted Sentiment: Positive

In [ ]:
import joblib

joblib.dump(model, "sentiment_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
from google.colab import files

files.download("product_classifier.h5")

FileNotFoundError: Cannot find file: product_classifier.h5

In [ ]:
!ls

sample_data  sentiment_model.pkl  vectorizer.pkl

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".h5") or file.endswith(".keras"):
            print(os.path.join(root, file))

In [13]:
model.save("product_classifier.h5")

AttributeError: 'LogisticRegression' object has no attribute 'save'

In [14]:
import os
print(os.path.exists("product_classifier.h5"))

False

In [15]:
model

LogisticRegression()

In [16]:
!pip install kaggle pandas numpy scikit-learn matplotlib

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [18]:
!kaggle datasets list -s "amazon reviews sentiment"

You must authenticate before you can call the Kaggle API.
Follow the instructions to authenticate at: https://github.com/Kaggle/kaggle-cli/blob/main/docs/README.md#authentication

In [19]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"dishagupta2004","key":"7b31ecfa0242f3eb8e22136f4887d40a"}'}

In [20]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [21]:
!kaggle datasets list -s "amazon reviews sentiment"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                             title                                                   size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  ------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
bittlingmayer/amazonreviews                                     Amazon Reviews for Sentiment Analysis              517080965  2019-11-18 02:50:34.600000         107908       1099  0.6875
tarkkaanko/amazon                                               amazon reviews for sentiment analysis                 595680  2022-07-21 10:43:26.310000          13037         88  0.85294116
miriamodeyianypeter/sentiment-analysis-amazon-product-reviews   Sentiment Analysis: Amazon Product Reviews           3067707  2024-03-25 14:58:57.317000           2295         31  0.9411765
sid321axn/amazon-alexa-reviews                                  Amazon Alexa Reviews                                  167607  2018-07-31 17:45:14.407000          28981        296  0.8235294
kritanjalijain/amazon-reviews                                   Amazon reviews                                    1389222210  2021-05-15 09:45:40.597000          43765        277  1
grikomsn/amazon-cell-phones-reviews                             Amazon Cell Phones Reviews                           9274620  2019-12-26 22:21:16.053000          22386        242  1
bharadwaj6/kindle-reviews                                       Amazon reviews: Kindle Store Category              550036223  2018-05-22 04:50:16.630000           9586        173  1
abdallahwagih/amazon-reviews                                    Amazon reviews                                      46491149  2023-10-16 18:25:58.730000           7021        120  1
meetnagadia/amazon-kindle-book-review-for-sentiment-analysis    Amazon Kindle Book Review for Sentiment Analysis     6686485  2021-09-03 11:52:29.630000           7073         61  1
datafiniti/consumer-reviews-of-amazon-products                  Consumer Reviews of Amazon Products                 17049423  2019-05-20 00:38:59.583000          67826        513  0.7647059
mrmars1010/iphone-customer-reviews-nlp                          Apple IPhone Customer Reviews                         358726  2024-09-22 02:14:40.933000           8014         93  1
mohamedbakhet/amazon-books-reviews                              Amazon Books Reviews                              1140283761  2022-09-13 23:04:08.787000          37608        241  1
grikomsn/lazada-indonesian-reviews                              Lazada Indonesian Reviews                            7004381  2019-10-02 15:19:33.287000           9235        107  1
PromptCloudHQ/toy-products-on-amazon                            Toy Products on Amazon                               8576250  2017-09-15 19:45:36.823000          13408        151  1
dongrelaxman/amazon-reviews-dataset                             Amazon Reviews Dataset                               4812639  2024-09-20 06:07:43.947000           8790         66  1
thedevastator/amazon-customer-reviews-with-2013-2019-sentiment  Amazon Customer Reviews with Sentiment               4286966  2023-01-15 14:29:09                   969         11  1
haoboxu/amazon-reviews-for-sentiment-analysis                   Amazon Reviews for Sentiment Analysis              296068558  2022-04-18 07:16:28.477000            542          6  0.875
lazylad99/amazon-e-commerce-product-and-review-dataset          Amazon E-commerce Products & Reviews Dataset         1956881  2025-03-12 09:32:14.650000           2528         38  1
mahmudulhaqueshawon/amazon-product-reviews                      Amazon Product Reviews                               1334427  2024-04-08 07:54:09.803000           2569         91  0.88235295
marklvl/sentiment-labelled-sentences-data-set                   Sentiment Labelled Sentences Data Set                 334104  2018-04-24 21:20:20.963000          24561        178  0.7058824

In [22]:
!kaggle datasets list -s "ecommerce reviews"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                        title                                                    size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------  -------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
olistbr/brazilian-ecommerce                                Brazilian E-Commerce Public Dataset by Olist         44717580  2021-10-01 19:08:27.970000         590643       4403                1
devsubhash/flipkart-mobiles-dataset                        Flipkart Mobiles Dataset                                55674  2022-03-20 10:46:28.567000          18296         99                1
imrulhasanrobi/e-commerce-big-dataset-from-multi-category  E-commerce big Dataset from Multi category (60k+)       64744  2023-03-06 16:14:10.813000           2292         37                1
nirant/nykaa-app-review-sentiment                          Nykaa App Review Sentiment                            3958995  2021-09-12 06:25:02.150000            764         12                1
promptcloud/walmart-product-data-2019                      Walmart Product Data 2019                            14308028  2020-04-14 06:19:43.813000           3619         30                1
lautarofrancetich/ecommerce-reviews                        ecommerce-reviews                                     2924120  2022-05-29 18:35:36.583000             96          2       0.29411766
jithinanievarghese/flipkart-smartphones-dataset            Flipkart Smartphones Dataset                            76982  2022-03-26 18:47:48.067000            633          8        0.8235294
trnduythanhkhttt/uelstoredataset                           Ecommerce Rating Dataset                              1282217  2022-03-21 15:04:21.540000           1131         17           0.6875
anvitkumar/shopping-dataset                                Ecommerce Dataset (Products & Sizes Included)         1274856  2026-07-31 00:39:03.243000           2510         23        0.7647059
kartikeybartwal/ecomerce-product-recommendation-dataset    Ecomerce Product Recommendation Dataset                 14092  2024-05-27 04:20:31.490000           1440         14                1
nicapotato/womens-ecommerce-clothing-reviews               Women's E-Commerce Clothing Reviews                   2924120  2018-02-03 19:59:19.153000          98928       1173       0.88235295
noopurbhatt/retail-product-catalog-dataset                 Retail Product Catalog Dataset                           1571  2026-04-03 20:21:02.037000            101          7        0.9411765
devsubhash/fitness-trackers-products-ecommerce             Fitness Trackers Products Ecommerce                     18203  2022-01-31 17:15:57.920000           4273         72                1
arnabchaki/fitness-trackers-products-ecommerce             Fitness Trackers Products Ecommerce ⌚                   14610  2023-03-23 09:15:56.427000           3681         51                1
jayeshsalunke101/brazilian-ecommerce-public-dataset        Brazilian E-Commerce Public Dataset                  44802190  2021-04-22 11:28:00.077000           1652         17       0.64705884
mehranamjad21/ecommerce-product-reviews                    Ecommerce product reviews                                3729  2025-09-28 07:32:29.713000              2          1       0.11764706
wearetenet/ecommerce-product-page-study                    Ecommerce Product Page Study                             1428  2025-07-13 16:17:50.063000             72          3        0.7058824
alpersah11/turkish-ecommerce-reviews-csv                   Turkish Ecommerce Reviews Dataset                     2642857  2025-08-22 08:13:25.610000             13          0        0.5294118
abhishekvinayake/ecommerce-sentiment-dataset-900k          Ecommerce Sentiment Dataset (900K+)                  47590105  2026-05-19 16:04:17.227000              6          2        0.7058824
lokareshrikant/flipkart-laptop-dataset                     Laptop dataset                                          42578  2022-06-28 17:47:39.770000            236          9        0.5882353

In [23]:
!kaggle datasets list -s "amazon reviews"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                  title                                           size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------  ---------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
kritanjalijain/amazon-reviews                        Amazon reviews                            1389222210  2021-05-15 09:45:40.597000          43765        277                1
abdallahwagih/amazon-reviews                         Amazon reviews                              46491149  2023-10-16 18:25:58.730000           7021        120                1
snap/amazon-fine-food-reviews                        Amazon Fine Food Reviews                   253873708  2017-05-01 18:51:31.490000         263905       2456        0.7941176
mohamedbakhet/amazon-books-reviews                   Amazon Books Reviews                      1140283761  2022-09-13 23:04:08.787000          37608        241                1
sid321axn/amazon-alexa-reviews                       Amazon Alexa Reviews                          167607  2018-07-31 17:45:14.407000          28981        296        0.8235294
eswarchandt/amazon-music-reviews                     Amazon Musical Instruments Reviews           4921881  2020-03-29 02:59:52.473000          23205        317                1
arhamrumi/amazon-product-reviews                     Amazon Product Reviews                     120062355  2021-07-11 17:40:05.393000          31948        131                1
grikomsn/amazon-cell-phones-reviews                  Amazon Cell Phones Reviews                   9274620  2019-12-26 22:21:16.053000          22386        242                1
bittlingmayer/amazonreviews                          Amazon Reviews for Sentiment Analysis      517080965  2019-11-18 02:50:34.600000         107908       1099           0.6875
dongrelaxman/amazon-reviews-dataset                  Amazon Reviews Dataset                       4812639  2024-09-20 06:07:43.947000           8790         66                1
saurav9786/amazon-product-reviews                    Amazon Product Reviews                     114817524  2020-01-14 13:25:53.247000          32615        184       0.64705884
yasserh/amazon-product-reviews-dataset               Amazon Product Reviews Dataset                725339  2022-01-23 17:21:16.690000          18265        105                1
PromptCloudHQ/amazon-reviews-unlocked-mobile-phones  Amazon Reviews: Unlocked Mobile Phones      34182461  2017-01-11 10:22:30.603000          18963        194                1
datafiniti/consumer-reviews-of-amazon-products       Consumer Reviews of Amazon Products         17049423  2019-05-20 00:38:59.583000          67826        513        0.7647059
bharadwaj6/kindle-reviews                            Amazon reviews: Kindle Store Category      550036223  2018-05-22 04:50:16.630000           9586        173                1
mahmudulhaqueshawon/amazon-product-reviews           Amazon Product Reviews                       1334427  2024-04-08 07:54:09.803000           2569         91       0.88235295
cynthiarempel/amazon-us-customer-reviews-dataset     Amazon US Customer Reviews Dataset       22497731749  2021-06-16 20:07:46.343000          23750        112                1
shitalkat/amazonearphonesreviews                     Amazon Earphones Reviews                      790804  2019-07-19 04:53:11.900000           4162         33                1
ashishkumarak/amazon-shopping-reviews-daily-updated  Amazon Shopping Reviews [Daily Updated]     10942559  2026-07-31 08:51:30.047000           6632         66                1
danielihenacho/amazon-reviews-dataset                Amazon Reviews Dataset                        982575  2023-01-02 07:19:57.750000           3187         20                1

In [24]:
!kaggle datasets list -s "customer reviews sentiment"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                              title                                                    size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  -------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
niraliivaghani/flipkart-product-customer-reviews-dataset         Flipkart Product reviews with sentiment Dataset       3970956  2023-02-03 09:21:11.847000          10589         58                1
nelgiriyewithana/mcdonalds-store-reviews                         McDonald's Store Reviews                              1868387  2023-06-19 08:46:00.263000          15622        218                1
burhanbilenn/duygu-analizi-icin-urun-yorumlari                   Duygu Analizi Veri Seti (Olumlu/Olumsuz/Tarafsız)      962550  2020-10-15 21:36:01.047000           3002         30                1
nicapotato/womens-ecommerce-clothing-reviews                     Women's E-Commerce Clothing Reviews                   2924120  2018-02-03 19:59:19.153000          98928       1173       0.88235295
sid321axn/amazon-alexa-reviews                                   Amazon Alexa Reviews                                   167607  2018-07-31 17:45:14.407000          28981        296        0.8235294
harshalhonde/starbucks-reviews-dataset                           Starbucks Reviews Dataset                              173724  2023-09-15 08:21:59.817000           9908         94                1
abdallahwagih/amazon-reviews                                     Amazon reviews                                       46491149  2023-10-16 18:25:58.730000           7021        120                1
bittlingmayer/amazonreviews                                      Amazon Reviews for Sentiment Analysis               517080965  2019-11-18 02:50:34.600000         107908       1099           0.6875
dongrelaxman/amazon-reviews-dataset                              Amazon Reviews Dataset                                4812639  2024-09-20 06:07:43.947000           8790         66                1
mansithummar67/flipkart-product-review-dataset                   Flipkart Products Review Dataset                      4074542  2023-01-26 13:08:59.517000           7376         61                1
grikomsn/amazon-cell-phones-reviews                              Amazon Cell Phones Reviews                            9274620  2019-12-26 22:21:16.053000          22386        242                1
kundanbedmutha/customer-sentiment-dataset                        Customer Sentiment Dataset                             296232  2025-11-19 08:18:50.493000           3243         49                1
thedevastator/amazon-customer-reviews-with-2013-2019-sentiment   Amazon Customer Reviews with Sentiment                4286966  2023-01-15 14:29:09                   969         11                1
jocelyndumlao/prdect-id-indonesian-emotion-classification        PRDECT-ID: Indonesian Emotion Classification           313471  2023-09-11 01:46:52.857000           3233        116                1
datafiniti/consumer-reviews-of-amazon-products                   Consumer Reviews of Amazon Products                  17049423  2019-05-20 00:38:59.583000          67826        513        0.7647059
mohankrishnathalla/mobile-reviews-sentiment-and-specification    Global Mobile Reviews Dataset (2025 Edition)          2211906  2025-10-22 16:01:13.550000           3765         64                1
burhanbilenn/turkish-customer-reviews-for-binary-classification  Duygu Analizi Veri Seti (Olumlu/Olumsuz)               676549  2020-11-05 08:37:20.367000            981         24                1
chaudharyanshul/airline-reviews                                  Airline Reviews                                       1358160  2023-11-23 01:44:49.477000           5564         46                1
kapturovalexander/consumer-sentiments-and-ratings                🏬🛍️😀 Consumer Sentiments and Ratings                  2692042  2025-02-26 09:03:08.910000           1543         29                1
juhibhojani/zomato-cafe-reviews                                  Zomato Cafe Reviews                                     61910  2023-08-18 10:17:37.967000           2354         53                1

In [25]:
!kaggle datasets list -s "customer reviews"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                       title                                                      size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------  --------------------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
vigneshwarsofficial/reviews                               Restaurant Customer Reviews                               24636  2019-07-26 14:44:02.480000          10792         64  0.9411765
mrmars1010/iphone-customer-reviews-nlp                    Apple IPhone Customer Reviews                            358726  2024-09-22 02:14:40.933000           8014         93  1
cynthiarempel/amazon-us-customer-reviews-dataset          Amazon US Customer Reviews Dataset                  22497731749  2021-06-16 20:07:46.343000          23750        112  1
olistbr/brazilian-ecommerce                               Brazilian E-Commerce Public Dataset by Olist           44717580  2021-10-01 19:08:27.970000         590643       4403  1
nicapotato/womens-ecommerce-clothing-reviews              Women's E-Commerce Clothing Reviews                     2924120  2018-02-03 19:59:19.153000          98928       1173  0.88235295
jagathratchakan/indian-airlines-customer-reviews          Indian Airlines Customer Reviews                         510316  2024-09-29 00:29:33.723000           1712         29  1
bhavikardeshna/amazon-customerreviews-polarity            Amazon Customer-Reviews Polarity                      700672680  2022-06-27 19:10:45.673000           2083         20  0.7941176
nelgiriyewithana/mcdonalds-store-reviews                  McDonald's Store Reviews                                1868387  2023-06-19 08:46:00.263000          15622        218  1
mohamedramadan2040/arabic-customer-reviews                Arabic Egypt Customer Reviews                           1254860  2024-11-29 15:52:16.783000            333         10  1
mehmetisik/amazon-review                                  Online Product Reviews Analysis: Customer Feedback       721801  2023-06-21 10:30:36.080000           3683        118  0.5882353
anshtanwar/top-200-trending-books-with-reviews            Top 100 Bestselling Book Reviews on Amazon               432142  2023-11-09 06:31:02.210000          18615        134  1
niraliivaghani/flipkart-product-customer-reviews-dataset  Flipkart Product reviews with sentiment Dataset         3970956  2023-02-03 09:21:11.847000          10589         58  1
roshansalunke/british-airways-customer-reviews            British Airways Customer Reviews                        1025906  2023-09-08 05:00:08.393000            569         15  0.9411765
atharvasoundankar/fashion-retail-sales                    🛍️ Fashion Retail Sales Dataset                           31656  2025-04-01 05:05:48.020000           9583         89  1
shahriarkabir/iphone-14-customer-reviews-dataset-ratings  iPhone 14 Customer Reviews Dataset                        46245  2024-03-02 12:30:50.800000            772         65  0.9411765
sid321axn/amazon-alexa-reviews                            Amazon Alexa Reviews                                     167607  2018-07-31 17:45:14.407000          28981        296  0.8235294
skillsmuggler/amazon-ratings                              Amazon - Ratings (Beauty Products)                     30243733  2018-06-24 09:49:57.787000          19779        154  1
eswarchandt/amazon-music-reviews                          Amazon Musical Instruments Reviews                      4921881  2020-03-29 02:59:52.473000          23205        317  1
burhanbilenn/duygu-analizi-icin-urun-yorumlari            Duygu Analizi Veri Seti (Olumlu/Olumsuz/Tarafsız)        962550  2020-10-15 21:36:01.047000           3002         30  1
harshalhonde/starbucks-reviews-dataset                    Starbucks Reviews Dataset                                173724  2023-09-15 08:21:59.817000           9908         94  1

In [26]:
!kaggle datasets list -s "amazon reviews"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                  title                                           size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------  ---------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
kritanjalijain/amazon-reviews                        Amazon reviews                            1389222210  2021-05-15 09:45:40.597000          43765        277                1
abdallahwagih/amazon-reviews                         Amazon reviews                              46491149  2023-10-16 18:25:58.730000           7021        120                1
snap/amazon-fine-food-reviews                        Amazon Fine Food Reviews                   253873708  2017-05-01 18:51:31.490000         263906       2456        0.7941176
mohamedbakhet/amazon-books-reviews                   Amazon Books Reviews                      1140283761  2022-09-13 23:04:08.787000          37608        241                1
sid321axn/amazon-alexa-reviews                       Amazon Alexa Reviews                          167607  2018-07-31 17:45:14.407000          28981        296        0.8235294
eswarchandt/amazon-music-reviews                     Amazon Musical Instruments Reviews           4921881  2020-03-29 02:59:52.473000          23205        317                1
arhamrumi/amazon-product-reviews                     Amazon Product Reviews                     120062355  2021-07-11 17:40:05.393000          31948        131                1
grikomsn/amazon-cell-phones-reviews                  Amazon Cell Phones Reviews                   9274620  2019-12-26 22:21:16.053000          22386        242                1
bittlingmayer/amazonreviews                          Amazon Reviews for Sentiment Analysis      517080965  2019-11-18 02:50:34.600000         107908       1099           0.6875
dongrelaxman/amazon-reviews-dataset                  Amazon Reviews Dataset                       4812639  2024-09-20 06:07:43.947000           8790         66                1
saurav9786/amazon-product-reviews                    Amazon Product Reviews                     114817524  2020-01-14 13:25:53.247000          32615        184       0.64705884
yasserh/amazon-product-reviews-dataset               Amazon Product Reviews Dataset                725339  2022-01-23 17:21:16.690000          18265        105                1
PromptCloudHQ/amazon-reviews-unlocked-mobile-phones  Amazon Reviews: Unlocked Mobile Phones      34182461  2017-01-11 10:22:30.603000          18963        194                1
datafiniti/consumer-reviews-of-amazon-products       Consumer Reviews of Amazon Products         17049423  2019-05-20 00:38:59.583000          67826        513        0.7647059
bharadwaj6/kindle-reviews                            Amazon reviews: Kindle Store Category      550036223  2018-05-22 04:50:16.630000           9586        173                1
mahmudulhaqueshawon/amazon-product-reviews           Amazon Product Reviews                       1334427  2024-04-08 07:54:09.803000           2569         91       0.88235295
cynthiarempel/amazon-us-customer-reviews-dataset     Amazon US Customer Reviews Dataset       22497731749  2021-06-16 20:07:46.343000          23750        112                1
shitalkat/amazonearphonesreviews                     Amazon Earphones Reviews                      790804  2019-07-19 04:53:11.900000           4162         33                1
ashishkumarak/amazon-shopping-reviews-daily-updated  Amazon Shopping Reviews [Daily Updated]     10942559  2026-07-31 08:51:30.047000           6632         66                1
danielihenacho/amazon-reviews-dataset                Amazon Reviews Dataset                        982575  2023-01-02 07:19:57.750000           3187         20                1

In [27]:
!kaggle datasets download -d nicapotato/womens-ecommerce-clothing-reviews

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/nicapotato/womens-ecommerce-clothing-reviews
License(s): CC0-1.0
Downloading womens-ecommerce-clothing-reviews.zip to /content
100% 2.79M/2.79M [00:00<00:00, 129MB/s]

In [28]:
!unzip womens-ecommerce-clothing-reviews.zip

Archive:  womens-ecommerce-clothing-reviews.zip
  inflating: Womens Clothing E-Commerce Reviews.csv

In [29]:
import os

print(os.listdir())

['.config', 'Womens Clothing E-Commerce Reviews.csv', 'vectorizer.pkl', 'womens-ecommerce-clothing-reviews.zip', 'sentiment_model.pkl', 'kaggle.json', 'sample_data']

In [30]:
import joblib

model = joblib.load("sentiment_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

review = ["The delivery was very late"]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print("Prediction:", prediction[0])

Prediction: Positive

In [31]:
import pandas as pd

df = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")

df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [32]:
print(df.columns)

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [33]:
import pandas as pd

df = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")

df = df[['Review Text', 'Rating']]

df.head()

                                         Review Text  Rating
0  Absolutely wonderful - silky and sexy and comf...       4
1  Love this dress!  it's sooo pretty.  i happene...       5
2  I had such high hopes for this dress and reall...       3
3  I love, love, love this jumpsuit. it's fun, fl...       5
4  This shirt is very flattering to all due to th...       5

In [34]:
df = df.dropna()

df.head()

                                         Review Text  Rating
0  Absolutely wonderful - silky and sexy and comf...       4
1  Love this dress!  it's sooo pretty.  i happene...       5
2  I had such high hopes for this dress and reall...       3
3  I love, love, love this jumpsuit. it's fun, fl...       5
4  This shirt is very flattering to all due to th...       5

In [35]:
def sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

df["Sentiment"] = df["Rating"].apply(sentiment)

df.head()

                                         Review Text  Rating Sentiment
0  Absolutely wonderful - silky and sexy and comf...       4  Positive
1  Love this dress!  it's sooo pretty.  i happene...       5  Positive
2  I had such high hopes for this dress and reall...       3   Neutral
3  I love, love, love this jumpsuit. it's fun, fl...       5  Positive
4  This shirt is very flattering to all due to th...       5  Positive

In [36]:
df["Sentiment"].value_counts()

Sentiment
Positive    17448
Neutral      2823
Negative     2370
Name: count, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split

X = df["Review Text"]
y = df["Sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 18112
Testing samples: 4529

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [39]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [40]:
from sklearn.metrics import accuracy_score, classification_report

predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))

print("\nClassification Report:\n")

print(classification_report(y_test, predictions))

Accuracy: 0.7650695517774343

Classification Report:

              precision    recall  f1-score   support

    Negative       0.45      0.62      0.52       474
     Neutral       0.33      0.49      0.39       565
    Positive       0.95      0.83      0.89      3490

    accuracy                           0.77      4529
   macro avg       0.58      0.65      0.60      4529
weighted avg       0.82      0.77      0.79      4529

In [41]:
import joblib

joblib.dump(model, "sentiment_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("Sentiment model saved successfully!")

Sentiment model saved successfully!

In [42]:
review = ["The delivery was very late"]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print(prediction[0])

Neutral

In [43]:
reviews = [
    "Excellent quality and perfect fitting",
    "Very poor quality and terrible fabric",
    "The dress is okay",
    "Loved the material",
    "Worst purchase ever",
    "Fits perfectly"
]

for r in reviews:
    pred = model.predict(vectorizer.transform([r]))
    print(r, "->", pred[0])

Excellent quality and perfect fitting -> Positive
Very poor quality and terrible fabric -> Negative
The dress is okay -> Negative
Loved the material -> Negative
Worst purchase ever -> Negative
Fits perfectly -> Positive

In [44]:
from google.colab import files

files.download("sentiment_model.pkl")
files.download("vectorizer.pkl")